before_build:
  - nuget restore
build_script:
  - choco install "msbuild-sonarqube-runner" -y
  - MSBuild.SonarQube.Runner.exe begin /k:"ebcdic-compare-tool" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=53b27a2d5e649f3709c2ac12936770c0804739fb" /d:sonar.cs.opencover.reportsPaths="opencover.xml" 
  - msbuild "CodeMovement.EbcdicCompare.sln"
  - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/noresults /noisolation /testcontainer:\".\CodeMovement.EbcdicCompare.UnitTests\bin\Debug\CodeMovement.EbcdicCompare.UnitTests.dll\"" -filter:"+[CodeMovement.EbcdicCompare*]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\opencover.xml
  - MSBuild.SonarQube.Runner.exe end /d:"sonar.login=53b27a2d5e649f3709c2ac12936770c0804739fb"